name: Build and Release Resume

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    paths:
      - '*.typ'
      - '!template.typ'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - name: Get the release version from the tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create ${{ env.VERSION }} --draft --verify-tag --title "Resume ${{ env.VERSION }}"
    outputs:
      version: ${{ env.VERSION }}

  build-resumes:
    name: Build Resumes
    needs: ['create-release']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Find Typst files
        id: find-typst-files
        run: echo "typst_files=$(ls *.typ | grep -v '^template.typ$' | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: Build resumes
        run: |
          for file in ${{ steps.find-typst-files.outputs.typst_files }}; do
            docker run --rm -i \
              --volume ${{ github.workspace }}:/mnt \
              --workdir "/mnt" \
              "ghcr.io/typst/typst:latest" \
              typst \
              compile \
              --font-path "./templates/latex/assets/fonts" \
              "$file" "${file%.*}.pdf"
          done

      - name: Generate SHA256 checksums
        run: |
          for pdf in *.pdf; do
            sha256sum "$pdf" > "${pdf}.sha256"
          done

      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          version="${{ needs.create-release.outputs.version }}"
          for pdf in *.pdf; do
            gh release upload "$version" "$pdf" "${pdf}.sha256"
          done

      - name: Upload Resumes as Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: resumes
          path: "*.pdf"
